# Generated by Django 4.2.9 on 2024-03-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_story_alter_report_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='story',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='stories/videos/'),
        ),
        migrations.DeleteModel(
            name='StoryMedia',
        ),
    ]
