# Generated by Django 4.2.9 on 2024-03-11 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_timestamp_story_created_at_story_caption_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
