# Generated by Django 4.2.9 on 2024-03-18 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_report_user_alter_userprofile_profile_pic_and_more'),
        ('api', '0008_alter_story_user'),
    ]

    operations = [
    ]
